### ISSUE TITLE
What role  does SNAC play in this framework?

### ISSUE THREAD

**Issue by AjianIronSide** [gpt-omni/mini-omni2#13]
Hi,

  I wonder what function does SNAC module actually have. Can we think it a TTS module or not ? Or what happen if  just not use SNAC or other codec module in the framework?

**Comment by mini-omni** [comment]
hi, we use SNAC to encode audio, and predict the snac tokens as the audio output. SNAC is an audio encodec method. If you  use other codec methods, like Encodec, you need to retrain the model to for adaptation.
