### ISSUE TITLE
How can we add human natural voice 

### ISSUE THREAD

**Issue by shubhamgajbhiye1994** [gpt-omni/mini-omni2#16]
How to add human natural voice if I want to be ..

**Comment by superFilicos** [comment]
Hi, do you mean that you want to train Mini-Omni with new data?

**Comment by mini-omni** [comment]
@shubhamgajbhiye1994 hi, you need to re-train the model with human dialogue dataset.

**Comment by shubhamgajbhiye1994** [comment]
ok , got it thanks.
