### ISSUE TITLE
Question for model inference code

### ISSUE THREAD

**Issue by Xin-Cheng-Wen** [gpt-omni/mini-omni2#34]
Question for model inference code: can we have audio, visual and text as inputs at the same time and then output either text or audio. (Input of text may as a background prompt for some tasks)

**Comment by mini-omni** [comment]
Hi, for now, we did not train with mixed input, so it may not work with mixed text + audio + image as input.

**Comment by Xin-Cheng-Wen** [comment]
Thank you for your answer!
