### ISSUE TITLE
Error opening input: No such file or directory - crash on start

### ISSUE THREAD

**Issue by zoldaten** [gpt-omni/mini-omni2#4]
python server.py (on Windows 10) gives:
```
[in#0 @ 0000024b20115740] Error opening input: No such file or directory
Error opening input file ./data/samples/vision_qa_audio.wav.
Error opening input files: No such file or directory
```

vision_qa_audio.wav should be formed by myself ?

**Comment by superFilicos** [comment]
let me check, please wait for moment.

**Comment by superFilicos** [comment]
sorry that they are lost when merging changes. we add them in /data/samples, and you can try it after add it.

**Comment by zoldaten** [comment]
i put fake vision_qa_audio.wav and vision_qa_image.jpg but still cant start even if i set flask to debug mode=True:
![2024-10-18_10h47_12](https://github.com/user-attachments/assets/951e1009-f240-4c98-b3cf-c1ce259226c7)

404 error

**Comment by mini-omni** [comment]
@zoldaten it seems you use the GET method to do the request, please try post mothed? The sever seems working, do the streamlit work?

**Comment by zoldaten** [comment]
ok. seems it`s working! didnt catch that i should start another terminal for app.
![2024-10-18_11h16_33](https://github.com/user-attachments/assets/b10c0135-be87-4f18-a955-c7d16cbe903f)

addition:
have to install `pip install streamlit-webrtc`
and there are gaps in online speech after it was made by system.
When i start playing a fragment on steamlit page there is no gaps and audio is clear.

**Comment by mini-omni** [comment]
great, I update the requirements. 
This issue is related to the computational platform. It appears that your testing platform can only generate 5 tokens per second. For real-time, uninterrupted responses on Streamlit, a theoretical minimum of 13 tokens per second is required. Of course, model inference can be optimized; currently, our model is using the original fp32 format. We hope that in the future, members of the community will be able to assist with further optimizations.

**Comment by zoldaten** [comment]
now it`s great enough!

and one more addition misleading in audio-video mode:
even if camera selected and access granted to it (and page reloaded) there is a wrong message on the web page:
![2024-10-18_11h35_18](https://github.com/user-attachments/assets/a9c40b58-c559-4c81-ba04-262ed01cf784)

it is not interfere in inference process just frustrate.

**Comment by mini-omni** [comment]
@zoldaten you need to click START to activate the video stream, we may a demo video later to better illustrate the process.
