### ISSUE TITLE
what's the ideal output for running inference_vision.py 

### ISSUE THREAD

**Issue by AjianIronSide** [gpt-omni/mini-omni2#5]
I started the server and run the inference_vision.py . The result is below. Is that the result is should be? The text is longer than the wav output.

<img width="865" alt="截屏2024-10-18 17 58 58" src="https://github.com/user-attachments/assets/1596d4de-2aaf-4275-9ac1-8d4398c79931">

**Comment by mini-omni** [comment]
Hi, if you use our sample image and query audio in the `data` dir, the output should be like
```
The person in the image appears to be a middle-aged man with a fair complexion. He has short, neatly combed gray hair and a receding hairline. His facial features include a prominent nose, thin lips, and a gentle smile. He is wearing a dark suit with a notched lapel, a white shirt, and a dark tie with diagonal stripes. The background is a neutral, dark color that provides a contrast to his light-colored suit. The overall impression is one of professionalism and formality.
```
And the output audio will cover all the output text. However, it will occur that the audio is shorter than the output text.

**Comment by isruihu** [comment]
I got the same output text as @AjianIronSide , where is the problem?
